# Generated by Django 4.2.30 on 2026-05-16 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(verbose_name='추첨일')),
                ('num1', models.PositiveIntegerField(blank=True, null=True)),
                ('num2', models.PositiveIntegerField(blank=True, null=True)),
                ('num3', models.PositiveIntegerField(blank=True, null=True)),
                ('num4', models.PositiveIntegerField(blank=True, null=True)),
                ('num5', models.PositiveIntegerField(blank=True, null=True)),
                ('num6', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_num', models.PositiveIntegerField(blank=True, null=True)),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.PositiveIntegerField()),
                ('n2', models.PositiveIntegerField()),
                ('n3', models.PositiveIntegerField()),
                ('n4', models.PositiveIntegerField()),
                ('n5', models.PositiveIntegerField()),
                ('n6', models.PositiveIntegerField()),
                ('selection_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], default='AUTO', max_length=6, verbose_name='구매 방식')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('rank', models.IntegerField(default=-1, verbose_name='당첨 등수')),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
