# Generated by Django 4.2.30 on 2026-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottoround',
            name='draw_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='추첨일'),
        ),
    ]
