# Generated by Django 4.2.30 on 2026-05-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotto', '0002_alter_lottoround_draw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottoround',
            name='bonus_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='draw_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='round_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='lotto_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround'),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='n6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='selection_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lottoticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
